version: "3.8"

services:
    jekyll:
        build: .
        container_name: my-jekyll-site
        ports:
            - "4000:4000"
        volumes:
            - .:/srv/jekyll
            # Add node_modules to the list of excluded folders
            - /srv/jekyll/vendor/bundle
            - /srv/jekyll/_site
            - /srv/jekyll/.jekyll-cache
            - /srv/jekyll/node_modules
